# Generated by Django 2.1.5 on 2021-05-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=120)),
                ('userBio', models.TextField(blank=True, null=True)),
                ('userAge', models.IntegerField()),
            ],
        ),
    ]
